// <auto-generated />
using System;
using InfraStructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraStructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107220500_PopulatingPortfolioItems")]
    partial class PopulatingPortfolioItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owner");

                    b.HasData(
                        new
                        {
                            Id = new Guid("343bc5c9-4005-4785-8321-d321de4e727f"),
                            Address = "Cairo",
                            Avatar = "avatar.jpg",
                            FullName = "MahmoudIsmail",
                            Profile = ".Net Core Developer"
                        });
                });

            modelBuilder.Entity("Core.Entities.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9cf4576-9e56-4a97-92d0-0d04c1285d5b"),
                            Description = "Playstation store app",
                            ImageUrl = "gps.png",
                            ProjectName = "Playstation"
                        },
                        new
                        {
                            Id = new Guid("2f0e97d1-f012-46d2-8859-8eae24306d0b"),
                            Description = "Dummy data",
                            ImageUrl = "flappy.png",
                            ProjectName = "Home"
                        },
                        new
                        {
                            Id = new Guid("1a980bad-dd0f-430f-a6ff-56f3feeba5e3"),
                            Description = "Ocean",
                            ImageUrl = "ecole.png",
                            ProjectName = "Sea"
                        },
                        new
                        {
                            Id = new Guid("da0c18e8-4744-476b-82be-30ead6e9e2ff"),
                            Description = "Some dummy data",
                            ImageUrl = "instagram.png",
                            ProjectName = "bla bla"
                        },
                        new
                        {
                            Id = new Guid("c16a1ec3-8473-4b18-8673-1f319c8ce9a1"),
                            Description = "Video Rental App",
                            ImageUrl = "commercial.png",
                            ProjectName = "Vidly"
                        },
                        new
                        {
                            Id = new Guid("1c8ac68d-48b6-40ab-8a32-d9f31783c0b4"),
                            Description = "BookStore App",
                            ImageUrl = "angry.png",
                            ProjectName = "Bookly"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
